INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Mr. Chocolate", 2, "M", "blue", "chill", true)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Rowdy", 2, M, "brown", "super chill", true)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Tabitha", 3, F, "blue", "relaxed", true)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Sergeant Brown", 5, F, "brown", "asleep", true)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Melissa", 8, F, "yellow", "fiesty", true)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Grinch", 100, M, "purple", "cranky", true)
INSERT INTO bears (name, age, gender, color, temperament, alive)
  VALUES ("Wendy", 2, F, "white", "nonchalant", true)
INSERT INTO bears (age, gender, color, temperament, alive)
  VALUES (10, M, "gold", "irritable", true)
